plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1

# Filter out Bastion Host - target only private Redis nodes
filters:
  tag:Role: redis-node
  instance-state-name: [running]

keyed_groups:
  - key: tags.OS
    prefix: os

compose:
  ansible_host: private_ip_address
  ansible_user: "tags.OS == 'ubuntu' | ternary('ubuntu', 'ec2-user')"
    