plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1

# Only target private instances tagged as Redis nodes
filters:
  instance-state-name: [running]
  tag:Role: redis-node

keyed_groups:
  - key: tags.OS
    prefix: os

compose:
  ansible_host: private_ip_address
  ansible_user: "('ubuntu' if (tags.get('OS') == 'ubuntu') else 'ec2-user')"
    